### ISSUE TITLE
camshift.launchを立ち上げて１０秒ぐらいすると画面が黒くなる

### ISSUE THREAD

**Issue by mirai05** [jsk-enshu/robot-programming#108]
```
roslaunch --screen opencv_apps camshift.launch image:=/camera/rgb/image_raw
```

として１０秒ぐらいすると、画面が黒くなります。
立ち上げた直後の画面は以下。何もしていないつもりだけど、スクロールバーが下（みんなは上）で、色も青い。

![screenshot from 2016-10-28 16 02 32](https://cloud.githubusercontent.com/assets/22876445/19797783/23be893c-9d28-11e6-9e9e-d0eab0445091.png)

camshiftのソースコードは

https://github.com/ros-perception/opencv_apps/blob/indigo/src/nodelet/camshift_nodelet.cpp

みてみるとGUIを出さないモードもあるので、まずはそれで動くか調べてみる。

**Comment by mirai05** [comment]
追記

[ WARN] [1477639187.934265187, 7875.530000000]: '/camshift' subscribes topics only with child subscribers.

このようなエラーが出たあと、画面が黒くなって動かなくなりました。

**Comment by k-okada** [comment]
あ、rostopic echo /camshift/track_box とか rosrun image_view2 ... とかしたら変わるかも

--
◉ Kei Okada


2016-10-28 16:21 GMT+09:00 mirai05 <notifications@github.com>:

**Comment by mirai05** [comment]
解決しました。
問題は、OpenCVのバージョンが違ったからで、元に戻すと動くようになりました。
