### ISSUE TITLE
11/29演習課題１（１１班）

### ISSUE THREAD

**Issue by nkg1995** [jsk-enshu/robot-programming#143]
追加してほしい機能

今回はturtlebotが班で1台ずつだったため、接続できるPCが限られました。
Wifi接続のように、同時にいくつかのPCとturtlebotを接続できる方法、
または一度接続すれば、たとえその後切断してもtopicデータ内容などが保存され引き続き確認が行えるような方法はありますでしょうか。
ご検討よろしくお願い致します。

**Comment by yuki-asano** [comment]
> Wifi接続のように、同時にいくつかのPCとturtlebotを接続できる方法、
wifi接続は演習2で行う予定です．
一台をturtlebotとつなぐ台車PCとして，その他の遠隔PCからアクセスします．

> または一度接続すれば、たとえその後切断してもtopicデータ内容などが保存され引き続き確認が行えるような方法はありますでしょうか。
要望の意図に完全にあっているか分かりませんが，
screenという機能を使うことで，遠隔PCから台車PCへのネットワーク接続が切れた状態でも台車PCでのrosの状態を保存することができます．
こちらも演習2で行います．
