### ISSUE TITLE
20161129kadai1-team13

### ISSUE THREAD

**Issue by verry619** [jsk-enshu/robot-programming#144]
追加してほしい機能：
turtlebotの位置や速度だけではなく、動いた距離を記録する機能があると便利。指令して動かそうとした距離と実際に動いた距離には微妙な誤差生まれてしまうため、その誤差を埋めるためにもそのような機能があると役に立つと思う。

**Comment by yuki-asano** [comment]
自己位置推定はロボットにとても重要です．
ロボットシステムの講義や演習3日目でそのような話題も出てくるので，勉強してみてください．

**Comment by verry619** [comment]
浅野 助教

お返事ありがとうございます。

はい。自分でも勉強してみようと思います。
次回以降の演習も楽しみにしております。

03-160302
堀部純司

2016/11/30 1:09 "Yuki Asano" <notifications@github.com>:
