### ISSUE TITLE
11月29日の課題１について（4班）

### ISSUE THREAD

**Issue by ayamiya** [jsk-enshu/robot-programming#148]
演習で使う分にはケーブルはもっと短い方が使いやすいので、初めから整理しやすいようにしてあるとうれしいです。
または整理するためのものを配ればチェックポイント１の４の意味ももっとありそうです。

**Comment by yuki-asano** [comment]
ケーブルをまとめるねじりっこを前のテーブルに置いておいたのですが，周知不足でした．
次回以降も置いておくので，自由に取りに来てください．
