### ISSUE TITLE
roscdができないことがある

### ISSUE THREAD

**Issue by uehara-mech** [jsk-enshu/robot-programming#155]
3班
・emacsのshellで、roscdによるディレクトリの移動ができないことがある
・それ以外にも、ubuntuの端末上でも、roscdを使っている時、Tabによる補完ができないことがある(source ~/catkin_ws/devel/setup.bashはやっている)

**Comment by Ill0510** [comment]
roscdはroscoreとかminimal.launchしてないとできなかったりする

**Comment by k-okada** [comment]
そういうことはないはずです．
```
$ complete | grep roscd
complete -o nospace -F _roscomplete_sub_dir roscd
```
となることを確認してみてください．だめ場合は ros-indigo-rosbashがインストールされていないか、source /opt/ros/indigo/setup.bash がされていないかです．

**Comment by yuki-asano** [comment]
> ・emacsのshellで、roscdによるディレクトリの移動ができないことがある

こちらに関しては，rosemacsは入っているでしょうか．
```
sudo apt-get install ros-indigo-rosemacs
```
で入ります．
一日目の資料の付録に書いてあります．

**Comment by k-okada** [comment]
rosemacsはshellとは関係なく
M-x r f でpackage + file名がつかえる、という機能かと思います．

--
◉ Kei Okada


2016-12-03 14:37 GMT+09:00 Yuki Asano <notifications@github.com>:
