### ISSUE TITLE
dynamixel AT-12Aの仕様についての質問

### ISSUE THREAD

**Issue by Ill0510** [jsk-enshu/robot-programming#163]
シリアル通信で直接サーボを動かしたいと思っているのですが、ボーレートが分からないので、どう設定されているかを知りたいです。
また、アームの角サーボに振られているIDはturtlebotについている状態だとどうなっているか、また返却するときはどのようにIDを振って返せばいいかも確認したいです。

**Comment by yuki-asano** [comment]
> シリアル通信で直接サーボを動かしたいと思っているのですが、ボーレートが分からないので、どう設定されているかを知りたいです。

ボーレートは、常識的な値になっていると思うので、
115200や57600などを通信できるか試してみてください。


> また、アームの角サーボに振られているIDはturtlebotについている状態だとどうなっているか、また返却するときはどのようにIDを振って返せばいいかも確認したいです。

最初は、根本から1,2,3,,,,,7が振られているはずです。(もしかしたら、0からかも)
返却時もそのように振ってください。
確認の仕方は演習資料の２日目に書いてあります。

**Comment by k-okada** [comment]
https://github.com/jsk-enshu/robot-programming/issues/162
も見て見て下さい
