### ISSUE TITLE
euslispで時間計測するためには

### ISSUE THREAD

**Issue by ayamiya** [jsk-enshu/robot-programming#165]
euslispで一定時間が経過したら行動を変更するプログラムを書きたいです。
ただ、時間経過中は元の行動を継続していたいのですが、どうすればいいですか。
time-nowとかsleepだと行動が停止してしまうのでうまくいきません。

**Comment by yuki-asano** [comment]
多分出来ました。
これで目的の動作はできそうでしょうか。

```
#!/usr/bin/env roseus

(ros::roseus "time-test")

(setq *passed-time* 0)

(do-until-key
 (setq before (ros::time-now))
 (unix::usleep (* 1000 1000))
 (setq after (ros::time-now))
 (setq delta-t (send (ros::time- after before) :to-sec))
 (setq *passed-time* (+ delta-t *passed-time*))
 (cond ((< *passed-time* 5)
        (format t "before 5sec (~A sec)~%" *passed-time*))
       ((> *passed-time* 5)
        (format t "after 5sec (~A sec)~%" *passed-time*)))
 )
```

![time](https://cloud.githubusercontent.com/assets/6872136/21417422/c28c35c2-c85d-11e6-8748-47f81b242188.png)


参考
http://wiki.ros.org/ja/ROS/Tutorials/WritingServiceClient(euslisp)

**Comment by k-okada** [comment]
かぶったけど、せっかくプログラム書いたので．．．
https://gist.github.com/k-okada/af04ff0f55e0251549c254ca893352b7

--
◉ Kei Okada


2016-12-22 15:47 GMT+09:00 Yuki Asano <notifications@github.com>:

**Comment by ayamiya** [comment]
ありがとうございます。
