### ISSUE TITLE
2018/11/9 演習課題１（９班）

### ISSUE THREAD

**Issue by nakaotatsuya** [jsk-enshu/robot-programming#253]
p8のチェックポイント１．２において充電LEDが点灯となっているが、実際は点滅であると思われます。

**Comment by k-okada** [comment]
@tongtybj 資料を修正したらCloseしてください．

**Comment by tongtybj** [comment]
修正しました。

![image](https://user-images.githubusercontent.com/3666095/48752872-bf32dd80-ecce-11e8-9a3e-5c9885aaaa7f.png)
