### ISSUE TITLE
課題01　わからないこと、追加してほしい機能、バグの報告

### ISSUE THREAD

**Issue by itomotoki** [jsk-enshu/robot-programming#314]
わからないこと
とりあえず講義資料通りに実行しただけなので何がわかっていて何がわかっていないのかわからない

追加してほしい機能
・機能というより課題で、遠隔PCをつかってソースコードを書く機会を増やしてほしい。turtlebotに繋いであるPCの所持者はやることが多い一方、遠隔PCを操作する側が待機時間になってしまうことが多かった。
・同じノード名のノードを2つ同時に実行することはできないことがわかった。かんたんにノード名を変えたり指定したりする機能がほしい。モノクロの画像と色付き画像を同時に出力できなかったことからわかった。

見つけたバグ
なぜか1回めに命令を送ったら動かずに2回めは動いたということがあった。

**Comment by mmurooka** [comment]
> とりあえず講義資料通りに実行しただけなので何がわかっていて何がわかっていないのかわからない

講義資料のコマンド部分だけでなく，Appendixも含めて一通り読んでみて，それでも何が分からないか分からなかったら，具体的に何をやろうとしてどんなエラーになっているかで報告してもらえると助かります．

>・機能というより課題で、遠隔PCをつかってソースコードを書く機会を増やしてほしい。turtlebot繋いであるPCの所持者はやることが多い一方、遠隔PCを操作する側が待機時間になってしまうことが多かった。

初回の3章までは車載PCのみで進めていましたが，そこから先のセンサ値をsubscribeして指令値をpublishするプログラムを書いたり，euslispでgo-velocityやinverse-kinematicsを使うプログラムは車載PCでも遠隔PCでも同じようにできる構成にしようとしているので，
> 遠隔PCを操作する側が待機時間になってしまう

が具体的にどのあたりで起こったか教えてもらえると嬉しいです．
（ロボットを起動するlaunchは車載PCで上げるしかないですがこれは仕方ないです．）


> ・同じノード名のノードを2つ同時に実行することはできないことがわかった。かんたんにノード名を変えたり指定したりする機能がほしい。

Rvizについては，https://github.com/jsk-enshu/robot-programming/issues/315 を参考にしてください．さらに一般のroslaunchでノード名が被らないようにするためには，http://wiki.ros.org/ja/roslaunch/XML の`$(anon name)`を参考にしてください．

> なぜか1回めに命令を送ったら動かずに2回めは動いたということがあった。

どのプログラムを上げたかによって対処は変わると思うので，具体的に打ったコマンドやその時のログも報告できると良いですね．
