### ISSUE TITLE
rosdep install と catkin build でのエラー

### ISSUE THREAD

**Issue by ktro4989** [jsk-enshu/robot-programming#320]
配布資料の流れに沿ってビルドしようとしたところ以下のようなエラーが起こりました。
$rosdep install --from-paths . --ignore-src -y -r
![Screenshot from 2020-04-10 17-00-35](https://user-images.githubusercontent.com/60615504/78975085-527fe380-7b4e-11ea-885e-2ef467b8de0e.png)
$catkin build
![Screenshot from 2020-04-10 17-02-56](https://user-images.githubusercontent.com/60615504/78975191-8d821700-7b4e-11ea-949a-205d94aeb347.png)
![Screenshot from 2020-04-10 17-03-04](https://user-images.githubusercontent.com/60615504/78975200-9246cb00-7b4e-11ea-926c-767fdc108ad2.png)
![Screenshot from 2020-04-10 17-03-07](https://user-images.githubusercontent.com/60615504/78975206-9541bb80-7b4e-11ea-8bf9-c6ec0ed7027c.png)

一応この状態でも、gazeboや制御ツールなどは問題なく動いてるように見えました。
updateなども試してから実行したのですが、改善しませんでした。

**Comment by k-okada** [comment]
以下の様にしてみてください．
```
cd catkin_ws/src
catkin clean -y
rm -fr linux_* libfree*
wstool mserge https://raw.githubusercontent.com/jsk-enshu/robot-programming/bbf6d8af5e90ffb09b40b6526b6a951887964085/.rosinstall.melodic
wstool update
catkin merge
```
ちなみにこのエラーの前にlibfreenctが，，というエラーが出そうなもんなんだけど，そういうのはなかったのかな．．．

**Comment by kotarouetake** [comment]
返信ありがとうございます。

上記を試してみたのですが、相変わらずビルド時にいくつかビルド失敗してしまいました(上記ではcatkin mergeとなっていますが、catkin buildで良かったでしょうか？catkin mergeだと”コマンドが見つかりませんでした”と出ました)

また、講義資料に従いゼロからワークスペース作成を行いlibfreenectに関するエラーが出ていないか確認しましたが、rosdep install の際に出たもの以外エラーとして出ているものが見つかりませんでした。

**Comment by k-okada** [comment]
いくつかtypoを直したのでもう一回試してください．`rosdep install`は`-r`オプションがついていますが，これは`rosdep install --help`とすると`  -r                    Continue installing despite errors.`と出てくるので，そこでのエラーは無視してよいです．
むしろ`catkin build`のところで`freenct`関連でエラーが出ると思ったんですが．．．
