### ISSUE TITLE
rqtのcontrollerプルダウンメニューが出てこない

### ISSUE THREAD

**Issue by ketaro-m** [jsk-enshu/robot-programming#328]
2020/10/12の演習資料の3.1にあるように環境構築をし、
`roslaunch dxl_armed_turtlebot dxl_armed_turtlebot_gazebo.launch`
として動力学シミュレータは立ち上げた後
`rqt --perspective-file enshu.perspective`
として制御ツールを立ち上げたのですが、controllerのプルダウンタブが出てきません。

画像にあるように、gazeboを立ち上げた際にcontrollerに関するエラーが出ているので、おそらくはこの辺りが問題だとは思うのですが、原因がわかりますでしょうか。
![Screenshot from 2020-10-04 11-18-19](https://user-images.githubusercontent.com/52503908/95007686-762f6c80-064d-11eb-8e9a-acc18443c648.png)

ちなみに
`rosservice call /controller_manager/list_controllers`
としたときの出力は
`ERROR: transport error completing service call: receive_once[/controller_manager/list_controllers]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'`
のようになります。

また、~/.ros/log/latest/　以下のログファイルや、gazeboを立ち上げたときのターミナル出力は以下に置いてあります。
https://gist.github.com/ketaro-m/52cfeeeffa0d5ecd4bffaeb4a50184db

**Comment by k-okada** [comment]
良い質問ですね．
重要そうなエラーメッセージ
https://gist.github.com/ketaro-m/52cfeeeffa0d5ecd4bffaeb4a50184db#file-controller_spawner-11-log-L53
で調べてみると以下があたりました．
https://answers.ros.org/question/360537/unknown-error-handler-name-rosmsg/
にかいてある以下を試すとどうでしょうか？
ちなみに現状のgenpyのバージョンを知りたければrosversion genpyとします．

sudo apt-get update && sudo apt-get upgrade

--
◉ Kei Okada



2020年10月4日(日) 14:26 Keitaro Murakami <notifications@github.com>:

**Comment by ketaro-m** [comment]
そのようにしたら直りました。
ありがとうございます。
