### ISSUE TITLE
No module named srv のエラー

### ISSUE THREAD

**Issue by lie-far-away** [jsk-enshu/robot-programming#338]
1005の資料の2.3節を行っているのですが、rosrunをすると下のようなエラーが出てしまい実行できません。
公式のチュートリアルを参考にしてCMakeLists.txtをいじってみたのですが解決できませんでした。

ちなみにcatkin buildとcatkin_makeの違いは何でしょうか。（チュートリアルでは、catkin_makeをしていました）

mech-user@ki00107:~/catkin_ws$ rosrun beginner_tutorials add_two_ints_server.py
Traceback (most recent call last):
  File "/home/mech-user/catkin_ws/src/beginner_tutorials/scripts/add_two_ints_server.py", line 2, in <module>
    from beginner_tutorials.srv import *
ImportError: No module named srv
[CMakeLists.txt](https://github.com/jsk-enshu/robot-programming/files/5360685/CMakeLists.txt)

**Comment by ishiguroJSK** [comment]
「2.2.2  Pythonでサービスサーバとクライアントを書く」のことかな？(僕が古い資料を見ている？)

エラー的にsrvが適切に生成されてないようで，
添付のCmakeLists.txt見ると，いろいろ足りない気がするけど，
「2.2.1サービスの作成」のあたりの
`add_service_files(FILES AddTwoInts.srv)`
とか
`generate_messages(DEPENDENCIES geometry_msgs)`
を反映してみよう．
あと「2.1  ROSサンプルプログラム」で
`catkin create pkg beginner_tutorials --catkin-deps std_msgs geometry_msgs rospy roscpp message_generation message_runtime`
を指定してCMakeLists.txtが自動生成されてるはずだから，
`find_package(catkin REQUIRED COMPONENTS std_msgs geometry_msgs rospy roscpp message_generation message_runtime)`
みたいな行がちゃんと存在してるかも確認しよう

公式のチュートリアルにも似たようなことが書いてあります
http://wiki.ros.org/action/fullsearch/ja/ROS/Tutorials/CreatingMsgAndSrv?action=fullsearch&context=180&value=linkto%3A%22ja%2FROS%2FTutorials%2FCreatingMsgAndSrv%22

> ちなみにcatkin buildとcatkin_makeの違いは何でしょうか

catkin buildはcatkin_makeの上位互換だと思ってくれて良いです．
違いは色々あって僕も把握しきれていませんが，依存関係に応じた並列ビルド周りが強化されているので，ワークスペース内に大量のパッケージがあるときなどに不可欠かと思います．
