### ISSUE TITLE
目当てのファイルの探し方

### ISSUE THREAD

**Issue by kohtaro246** [jsk-enshu/robot-programming#341]
今週の課題に限らずなのですが、編集したいファイルがどこに入っているのかわからず、探すのに苦労しています。例えばubuntuのファイル検索機能を使って"teleop_twist_keyboard.py"と検索してもヒットしません。よい検索方法をご教示いただけますでしょうか。

**Comment by ishiguroJSK** [comment]
```
sudo updatedb
locate aaa.py
```
とかがシステム全体をそこそこ高速に検索できます(ファイルに変更が無い限りupdatedbは不要)

ただ，10/12の資料のsend_goal_actionlib.pyに関しては自分で作るという流れと思われます．
そしてどこに置くかということに関しては，
本来パスが正しく設定されていればROSのpythonスクリプトはどこに置いて実行してもよいのですが，
enshu_ws内に新しくパッケージを作って置くか，dxl_armed_turtlebotなどの既存のパッケージの中に置くか，
あたりになるかと思います．

**Comment by kohtaro246** [comment]
ありがとうございます。教えていただいた方法でteleop_twist_keyboardを検索したところ、見つけることができました。
