### ISSUE TITLE
10/12の資料の1~2ページ目について

### ISSUE THREAD

**Issue by Hakidame0102** [jsk-enshu/robot-programming#343]
6ページの手順に従ってenshu_wsを作成し, 2.1を実行しようとしたところ, シミュレーションの画面を立ち上げることができず, 次のようになりました. どこかの手順で間違えているのでしょうか.
![Screenshot from 2020-10-15 23-27-33](https://user-images.githubusercontent.com/67830606/96143516-1f277280-0f3e-11eb-9ccc-16858c277f0a.png)

**Comment by ishiguroJSK** [comment]
amclがamc1になってます．コマンドの途中でTabキーを押すと補完が効いて打ち間違えが減ります

**Comment by Hakidame0102** [comment]
打ち直したところ解決しました. ありがとうございました.
