### ISSUE TITLE
ubuntuが起動しなくなった

### ISSUE THREAD

**Issue by lie-far-away** [jsk-enshu/robot-programming#347]
学科pcのubuntuがフリーズしてしまったため、強制的に電源を切ったあと起動しようとすると、パスワード入力の画面までは表示されるのですがパスワードを入力すると、紫色一色の画面にマウスポインタが表示されるのみでなにもできない状態になってしまいました。windowsの方は問題なく起動するため、ubuntuのguiがうまく起動していないのだと思います。

ちなみにフリーズしたのは学科pcを外部モニターにつないで作業していて、下のリンクの記事を参考にしてfcitxを用いてワイヤレスのusキーボードを導入している最中でした。（どこが関係しているかわかりませんが）
[https://qiita.com/AnchorBlues/items/beeb40593fd4c579dbe5](https://qiita.com/AnchorBlues/items/beeb40593fd4c579dbe5)

**Comment by k-okada** [comment]
最初にOSを選ぶ画面があるとおもいますが、そこで上から二番目を選んでください。

https://www.maketecheasier.com/boot-recovery-mode-ubuntu/
でrootを選択。
1) qiita みて作業した内容を取り消す。'apt-get remove... 'する
2) 他にいくつか復帰できるかもしれない方法はあるので、連絡ください。

**Comment by lie-far-away** [comment]
rootでapt-get remove fcitx fcitx-mozcとしてみましたが未だ起動しません。

**Comment by k-okada** [comment]
$su mech-user
でmechユーザになれるとおもうけど，そこで
$ls -al
$cat .xinputrc
$ls -al .local/share/xorg
$cat  .local/share/xorg/Xorg.0.log
$ls -al /etc/X11

家，近ければ学校に来るのが早いかも

**Comment by lie-far-away** [comment]
対応していただきありがとうございました。
