### ISSUE TITLE
反復オペレータdoについて

### ISSUE THREAD

**Issue by kohtaro246** [jsk-enshu/robot-programming#351]
教材に載っているshow-squaresやhttp://www.nct9.ne.jp/m_hiroi/clisp/abcl05.htmlにのっているdoをつかったプログラムをemacs lispで動かそうとすると、写真のようなエラーが出ます。原因をご教示いただけると幸いです。
![Screenshot from 2020-10-23 17-03-03](https://user-images.githubusercontent.com/67863406/96972894-17755880-1552-11eb-8fe2-ee8117c5c400.png)

**Comment by ishiguroJSK** [comment]
全然詳しくないんだけど，emacs lispってcommon lispと結構違うという認識で，common lispとかeuslispのコードはいろいろ動かないとは思います．

**Comment by kohtaro246** [comment]
あ、そうなんですか！！
てっきりlispだったらなんでも同じかと思ってました。

**Comment by k-okada** [comment]
emacs lisp だと
```
(cl-do ((i 0 (+ i 1)))
    ((> i 10) 'done)
  (print i))
```
ですね．

プログラム言語の仕様と実装は異なるモノ，というのが結構一般的で
C言語なんかもGCCとMicroSoftのもので微妙に違ったりします．
例：https://easyaspi314.github.io/gcc-vs-clang.html

**Comment by kohtaro246** [comment]
ありがとうございます。
