### ISSUE TITLE
inconsistent face settingerr:

### ISSUE THREAD

**Issue by kohtaro246** [jsk-enshu/robot-programming#352]
このエラーはなぜ起きるのでしょうか。
コード：https://gist.github.com/kohtaro246/b7fad841b134d2904e9770155f2ab10b
エラー画面
![Screenshot from 2020-10-28 16-22-45](https://user-images.githubusercontent.com/67863406/97404686-d60df000-1939-11eb-9ced-0f637a2f3f0c.png)

**Comment by k-okada** [comment]
遅くなりました．
面と面が重なっているところの`body-`は上手く行かないことが多いです．
```
    ;;make-handle                                                                                                       
    (setq b4 (make-cube 60 10 3))
    (setq b3 (make-cube 54 6 5))
    (send b4 :locate #f(30 -5 38.5))
    (send b3 :locate #f(30 -3.5 38.5))
    (setq b4 (body- b4 b3))
    (setq b1 (body+ b1 b4))
```
などと，少し値を変えてあげると上手く動きます．

**Comment by kohtaro246** [comment]
解決しました。ご返信ありがとうございます。
