### ISSUE TITLE
10/26の資料p8のservo-modelクラスについて

### ISSUE THREAD

**Issue by ketaro-m** [jsk-enshu/robot-programming#358]
10/26の資料p8に下のようにあり、`rtmodel.l で実装されているクラスの概要．打ち込まないこと．`とあるのですが、これはcascaded-linkクラスは打ち込まず、servo-modelクラスは自分で書き込めということでしょうか？
初めに何も打ち込まずに、`(setq r (instance servo-model :init))`とだけするとエラーが出たので、[https://github.com/euslisp/jskeus/blob/master/irteus/irtmodel.l](https://github.com/euslisp/jskeus/blob/master/irteus/irtmodel.l)を覗いてみたところ、servo-modelクラスは存在していなかったので、このクラスだけ作成し、さらにその中で使われているmake-servoやmake-hinjiといった関数もp6~7にかけて存在しているので、その通りに打ち込むとオブジェクトを作ることができました。
このような解釈であっていますか？

また、もしそうだとしたら、資料の文言が若干分かりにくいような気がするので、上記のことを反映していただけると来年以降の僕のように混乱する学生が減るのではないかと思うのですが、いかがでしょうか。

![Screenshot from 2020-11-01 11-58-07](https://user-images.githubusercontent.com/52503908/97794150-9006a400-1c39-11eb-84c3-e36e325dd7e4.png)

**Comment by k-okada** [comment]
はい，その解釈であっています．

７ページに書いてある方法で，ベタ書きでロボットモデルは生成出来ているはずなので，
これをそのままクラス定義の中に入れる，という作業をすることを期待しています．
脂漏は直しておきます．
--
◉ Kei Okada



2020年11月1日(日) 12:06 Keitaro Murakami <notifications@github.com>:

**Comment by ketaro-m** [comment]
お返事ありがとうございます。
