### ISSUE TITLE
11/02課題2について

### ISSUE THREAD

**Issue by ham-sh** [jsk-enshu/robot-programming#367]
roslaunch dxl_armed_turtlebot dxl_armed_turtlebot_navigation.launch
を立ち上げてから、実行するとのことでしたが、私は自立移動デモプログラムを起動して上のlaunchファイルは実行させずに自分で書いたプログラムのみを実行させました。
すると画像のようにロボットが移動したのですがそれでもよろしいのでしょうか？

![Screenshot from 2020-11-03 23-03-23](https://user-images.githubusercontent.com/67727558/97996597-4ed5e600-1e2b-11eb-8204-b912d657d560.png)

**Comment by k-okada** [comment]
はい，これでOKです．ちゃんと動いていますね．
--
◉ Kei Okada



2020年11月3日(火) 23:26 ham-sh <notifications@github.com>:

**Comment by ham-sh** [comment]
ありがとうございます！
