### ISSUE TITLE
フィボナッチについて

### ISSUE THREAD

**Issue by ummaaa** [jsk-enshu/robot-programming#372]
11/2資料10ページのfibonacci-client.lはどこにおけばいいのでしょうか。色んな所を試したのですが、
rosrun beginner_tutorials fibonacci-client.l
とすると以下のようなエラーが出てしまいます。roscoreとsetup.bashはやりました。

[rosrun] Couldn't find executable named fibonacci-client.l below /home/mech-user/catkin_ws/src/beginner_tutorials
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/mech-user/catkin_ws/src/beginner_tutorials/euslisp/scripts/fibonacci-client.l
[rosrun]   /home/mech-user/catkin_ws/src/beginner_tutorials/euslisp/fibonacci-client.l
[rosrun]   /home/mech-user/catkin_ws/src/beginner_tutorials/fibonacci-client.l

**Comment by k-okada** [comment]
chmod u+x して実行ビットを付与してみてください
--
◉ Kei Okada


2020年11月6日(金) 11:29 ummaaa <notifications@github.com>:

**Comment by ummaaa** [comment]
ありがとうございます。
