### ISSUE TITLE
1102 課題５

### ISSUE THREAD

**Issue by kohtaro246** [jsk-enshu/robot-programming#377]
夜分遅くにすみません。
課題５（発展課題）でチェッカーボードがみえたらアームを伸ばし、見えなくなったらreset-pose2に戻すというプログラムまではできたのですが、turtlebotからみたチェッカーボードの相対位置をどのように利用すれば「一定距離まで近づき、手を伸ばす」という動作を実現できるのかわからず、つまっています。

試したこと：(send target-world  :pos)で相対位置のfloat-vectorが得られそうということがわかったので、float-vectorのx,y成分を抽出する。そして:go-velocityをつかってちかくまで移動するか、:go-posもあるようなので、これをかつようするかをしようとおもいましたが、float-vectorから要素を抽出する方法がわかりませんでした。

コード：
https://gist.github.com/kohtaro246/4a3041ad2acf32fb2aca08e26f320371

できたところまでの実行の様子：
![Screenshot from 2020-11-08 23-48-29](https://user-images.githubusercontent.com/67863406/98468245-fa60ab00-221c-11eb-8530-d87fea40cf95.png)
![Screenshot from 2020-11-08 23-48-16](https://user-images.githubusercontent.com/67863406/98468247-fc2a6e80-221c-11eb-8402-71de2d5cf92a.png)

**Comment by ishiguroJSK** [comment]
要素を取り出すだけなら
```
irteusgl$ (elt (float-vector 1 2 3) 2)
3.0
```
とかですね

**Comment by kohtaro246** [comment]
夜遅くにもかかわらず早急なお返事ありがとうございます。
うまくいきました。
