### ISSUE TITLE
sudo easy_install cythonができない

### ISSUE THREAD

**Issue by ummaaa** [jsk-enshu/robot-programming#378]
sudo easy_install cython
とすると
sudo: easy_install: コマンドが見つかりません
と出るのですが、どうすれば正しく動くでしょうか。

**Comment by k-okada** [comment]
多分既にcythonが入っていなるので，ここはスキップしてもらってよいかと思います．
もし入っていなかったら
sudo apt install cython
としてみてください．
--
◉ Kei Okada



2020年11月11日(水) 20:29 ummaaa <notifications@github.com>:

**Comment by ummaaa** [comment]
emacsでpython-modeに設定したら行けました。
ありがとうございました。
