### ISSUE TITLE
第6回の行動計画について

### ISSUE THREAD

**Issue by kamiharu04323** [jsk-enshu/robot-programming#415]
"sample-domain.pddl"というファイルに資料10p、11pのコードをコピペして"rosrun ff ff -f sample-problem.pddl -o sample-domain.pddl"で実行したのですが
"ff: parsing domain file
domain 'MANIP' defined

sample-domain.pddl: syntax error in line 57, '(':
domain definition expected"というエラーがでました。
ファイルの中身は以下のようになっています。57行目は"(define (problem sample)"となっているのですがどのように解決すればよいでしょうか。(pddlだと貼り付けできないみたいなのでtxtに一時的に変えています)
[sample-domain.txt](https://github.com/jsk-enshu/robot-programming/files/7579221/sample-domain.txt)

**Comment by kamiharu04323** [comment]
マルチエージェントプランニングの方と同様にファイルを2つに分けると動きました。失礼しました。

**Comment by k-okada** [comment]
よかたったです．domain ファイルにはドメイン（分野）を，problem ファイルは問題をかいて，問題が変わったらproblem ファイルだけ変えれば良いようになっているので，別のproblemを作ってみると良いとおもいます．
