### ISSUE TITLE
urdfモデルはありますか

### ISSUE THREAD

**Issue by kimhc6028** [jsk-enshu/robot-programming#48]
@snozawa 先生、このロボットのurdfモデルはありますか？

cc: @k-okada

**Comment by k-okada** [comment]
https://github.com/jsk-enshu/robot-programming/pull/53 に追加しました．
https://github.com/jsk-enshu/robot-programming
みて，使ってみて下さい．
roslaunch dxl_armed_turtlebot dxl_armed_turtlebot_gazebo.launch 
で立ち上がります．

モデル，チョット（かなり）手を抜いたので，軸間の距離が正しいかk，
細かいパーツやマスパラメータ等入れてもらえると嬉しいです．

**Comment by kimhc6028** [comment]
ありがとうございます。詳しい調整は頑張ってやってみます。
後、https://github.com/dgossow/dynamixel_urdfがrobot_programmingに入ってないようですが…

**Comment by k-okada** [comment]
https://github.com/jsk-enshu/robot-programming
のreadmeを見て下さい

```
$ wstool set robot-programming https://github.com/jsk-enshu/robot-programming --git -t src
$ wstool set dynamixel_urdf    https://github.com/jsk-enshu/dynamixel_urdf    --git -t src
```

**Comment by kimhc6028** [comment]
ごめんなさい。gripperつけるところに詰まっちゃています…
