### ISSUE TITLE
linux_hardware が indigo にはない

### ISSUE THREAD

**Issue by k-okada** [jsk-enshu/robot-programming#51]
ので，https://github.com/k-okada/robot-programming/commit/5d3f0a4c7ff61c4a51b254bdfa933b58df90df15
が必要でした．

indigo 以降ではlinux_peripheral_interface or smart_battery_msgs　を使うということで，
アップデートしておいてもらえると嬉しいです．

@snoawaに assign しておきますが，誰かに降っていいともいます．

**Comment by snozawa** [comment]
遅くなりましたが、こちらありがとうございました。

> indigo 以降ではlinux_peripheral_interface or smart_battery_msgs　を使うということで，
> アップデートしておいてもらえると嬉しいです．

こちらも承知しました。
