### ISSUE TITLE
URDFにwheel_left_linkとwheel_right_linkがありません

### ISSUE THREAD

**Issue by knorth55** [jsk-enshu/robot-programming#55]
![screenshot from 2015-11-11 10 25 33](https://cloud.githubusercontent.com/assets/9300063/11081382/7a62ce12-885f-11e5-8054-9d50ffddaf73.png)
rvizするとwheel_left_linkとwheel_right_linkが読み込めませんでした。

**Comment by k-okada** [comment]
#59で直しました
![screenshot from 2015-11-11 12 37 02](https://cloud.githubusercontent.com/assets/493276/11083770/9a3597d0-8876-11e5-9e6c-9859dcf5959d.png)
