### ISSUE TITLE
msgファイルをimportできません。

### ISSUE THREAD

**Issue by iZuno-K** [jsk-enshu/robot-programming#88]
mech-user@test1-pc:~/catkin_ws/src/beginner_tutorials/scripts$ python talker2.py 
Traceback (most recent call last):
  File "talker2.py", line 5, in <module>
    from beginner_turtorials.msg import Hello
ImportError: No module named beginner_turtorials.msg

行ったコマンド
catkin create pkg beginner_tutorials --catkin-deps std_msgs geometry_msgs rospy roscpp message_generation message_runtime
cd ~/catkin_ws/
catkin build

source ~/catkin_ws/devel/setup.bash
roscd beginner_tutorials

mkdir msg
Hello.msg追加

mkdir scripts
talker.pyとtalker2.pyを追加

Cmakelistに追加
「catkin_package(」よりも前に
add_message_files(FILES Hello.msg)
generate_messages(DEPENDENCIES geometry_msgs)

最後の行に
add_executable(listener src/listener.cpp)
target_link_libraries(listener ${catkin_LIBRARIES})

add_executable(listener2 src/listener2.cpp)
target_link_libraries(listener2 ${catkin_LIBRARIES})

cd scripts

chmod u+x ./talker2.py

別のターミナルで
roscore

pthon talker2.py

**Comment by k-okada** [comment]
`beginner_turtorials` は　`beginner_tutorials`の間違いでした．
